# config/services.yaml

parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        # Exclure les r√©pertoires qui ne contiennent pas de services
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration explicite du service ImageService
    App\Service\ImageService:
        arguments:
            $projectDir: '%kernel.project_dir%'
